name: Test Build

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        options:
          - 'windows-2022'
          - 'windows-2019'
        description: 'Operating System'
        required: false
        default: 'windows-2022'

  # Do not include "push" in final version (uncomment for testing on users own repo)
  # push:

  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.10.*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

  schedule:
    - cron: "0 0 * * *"

jobs:

  build-workflow-dispatch:
    if: ${{ contains('workflow_dispatch', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: ${{ inputs.os }}
    secrets: inherit

  build-gh_runner-windows-2022:
    if: ${{ contains('pull_request,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: windows-2022
    secrets: inherit

  build-gh_runner-windows-2019:
    if: ${{ contains('schedule,push', github.event_name) }}
    uses: ./.github/workflows/build-gh_runner.yml
    with:
      os: windows-2019
    secrets: inherit
